//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.6.1055.0。
// 
namespace QM.Demo.Quituser
{ 
/// <remarks/>
// CODEGEN: 未处理命名空间“http://www.w3.org/2000/wsdl/suds”中的可选 WSDL 扩展元素“method”。
// CODEGEN: 未处理命名空间“http://www.w3.org/2000/wsdl/suds”中的可选 WSDL 扩展元素“method”。
// CODEGEN: 未处理命名空间“http://www.w3.org/2000/wsdl/suds”中的可选 WSDL 扩展元素“class”。
// CODEGEN: 未处理命名空间“http://www.w3.org/2000/wsdl/suds”中的可选 WSDL 扩展元素“class”。
// CODEGEN: 未处理命名空间“http://www.w3.org/2000/wsdl/suds”中的可选 WSDL 扩展元素“class”。
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MsgHandlerBinding", Namespace="http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer/ProtocolInterfacer%2C" +
    "%20Version%3D1.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3Dnull")]
[System.Xml.Serialization.SoapIncludeAttribute(typeof(UserInfo))]
public partial class MsgHandlerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback InitializeLifetimeServiceOperationCompleted;
    
    private System.Threading.SendOrPostCallback RequestGateWayOperationCompleted;
    
    /// <remarks/>
    public MsgHandlerService() {
        this.Url = "http://10.68.10.59:12005/ProtocolInterfacer.bin";
    }
    
    /// <remarks/>
    public event InitializeLifetimeServiceCompletedEventHandler InitializeLifetimeServiceCompleted;
    
    /// <remarks/>
    public event RequestGateWayCompletedEventHandler RequestGateWayCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer.MsgHandler/ProtocolIn" +
        "terfacer#InitializeLifetimeService", RequestNamespace="http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer.MsgHandler/ProtocolIn" +
        "terfacer", ResponseNamespace="http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer.MsgHandler/ProtocolIn" +
        "terfacer")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public object InitializeLifetimeService() {
        object[] results = this.Invoke("InitializeLifetimeService", new object[0]);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginInitializeLifetimeService(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("InitializeLifetimeService", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public object EndInitializeLifetimeService(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void InitializeLifetimeServiceAsync() {
        this.InitializeLifetimeServiceAsync(null);
    }
    
    /// <remarks/>
    public void InitializeLifetimeServiceAsync(object userState) {
        if ((this.InitializeLifetimeServiceOperationCompleted == null)) {
            this.InitializeLifetimeServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeLifetimeServiceOperationCompleted);
        }
        this.InvokeAsync("InitializeLifetimeService", new object[0], this.InitializeLifetimeServiceOperationCompleted, userState);
    }
    
    private void OnInitializeLifetimeServiceOperationCompleted(object arg) {
        if ((this.InitializeLifetimeServiceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.InitializeLifetimeServiceCompleted(this, new InitializeLifetimeServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer.MsgHandler/ProtocolIn" +
        "terfacer#RequestGateWay", RequestNamespace="http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer.MsgHandler/ProtocolIn" +
        "terfacer", ResponseNamespace="http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer.MsgHandler/ProtocolIn" +
        "terfacer")]
    [return: System.Xml.Serialization.SoapElementAttribute("return")]
    public ResultSet RequestGateWay(string pFuncName, string pMachineName, UserInfo[] pUserInfo, bool pFlag) {
        object[] results = this.Invoke("RequestGateWay", new object[] {
                    pFuncName,
                    pMachineName,
                    pUserInfo,
                    pFlag});
        return ((ResultSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRequestGateWay(string pFuncName, string pMachineName, UserInfo[] pUserInfo, bool pFlag, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("RequestGateWay", new object[] {
                    pFuncName,
                    pMachineName,
                    pUserInfo,
                    pFlag}, callback, asyncState);
    }
    
    /// <remarks/>
    public ResultSet EndRequestGateWay(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ResultSet)(results[0]));
    }
    
    /// <remarks/>
    public void RequestGateWayAsync(string pFuncName, string pMachineName, UserInfo[] pUserInfo, bool pFlag) {
        this.RequestGateWayAsync(pFuncName, pMachineName, pUserInfo, pFlag, null);
    }
    
    /// <remarks/>
    public void RequestGateWayAsync(string pFuncName, string pMachineName, UserInfo[] pUserInfo, bool pFlag, object userState) {
        if ((this.RequestGateWayOperationCompleted == null)) {
            this.RequestGateWayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestGateWayOperationCompleted);
        }
        this.InvokeAsync("RequestGateWay", new object[] {
                    pFuncName,
                    pMachineName,
                    pUserInfo,
                    pFlag}, this.RequestGateWayOperationCompleted, userState);
    }
    
    private void OnRequestGateWayOperationCompleted(object arg) {
        if ((this.RequestGateWayCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.RequestGateWayCompleted(this, new RequestGateWayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer/ProtocolInterfacer%2C" +
    "%20Version%3D1.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3Dnull")]
public partial class UserInfo {
    
    private string idField;
    
    private string nameField;
    
    private string passwordField;
    
    private int privilegeField;
    
    private bool enabledField;
    
    private string cardNoField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public int Privilege {
        get {
            return this.privilegeField;
        }
        set {
            this.privilegeField = value;
        }
    }
    
    /// <remarks/>
    public bool Enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    public string CardNo {
        get {
            return this.cardNoField;
        }
        set {
            this.cardNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.SoapTypeAttribute(Namespace="http://schemas.microsoft.com/clr/nsassem/ProtocolInterfacer/ProtocolInterfacer%2C" +
    "%20Version%3D1.0.0.0%2C%20Culture%3Dneutral%2C%20PublicKeyToken%3Dnull")]
public partial class ResultSet {
    
    private bool seccessFlagField;
    
    private string keyField;
    
    private string resultField;
    
    private string descriptionField;
    
    /// <remarks/>
    public bool SeccessFlag {
        get {
            return this.seccessFlagField;
        }
        set {
            this.seccessFlagField = value;
        }
    }
    
    /// <remarks/>
    public string Key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    public string Result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void InitializeLifetimeServiceCompletedEventHandler(object sender, InitializeLifetimeServiceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class InitializeLifetimeServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal InitializeLifetimeServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void RequestGateWayCompletedEventHandler(object sender, RequestGateWayCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class RequestGateWayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal RequestGateWayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ResultSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ResultSet)(this.results[0]));
        }
    }
}

}